djangoApp/urls.py
from django.urls import path
from .views import AppListView, AppDetailView, AppCreateView, AppUpdateView, AppDeleteView

urlpatterns = [
  path('', AppListView.as_view(), name='djangoApp_list'),
  path('<int:pk>', AppDetailView.as_view(), name='djangoApp_detail'),
  path('create', AppCreateView.as_view(), name='djangoApp_create'),
  path('<int:pk>/update', AppUpdateView.as_view(), name='djangoApp_update'),
  path('<int:pk>/delete', AppDeleteView.as_view(), name='djangoApp_delete'),
]

django_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("pages/", include("pages.urls")),
    path("", include("djangoApp.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.email

djangoApp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

class DjangoApp(models.Model):
  title = models.CharField(max_length=255)
  body = models.TextField(default='1. #Todo goes here')
  author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
  
  def __str__(self):
    return self.title
  
  def get_absolute_url(self):
    return reverse('djangoApp_detail', args=[str(self.id)])

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email', 'username',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username',)

djangoApp/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import DjangoApp
from django.urls import reverse_lazy

class AppListView(ListView):
  template_name = 'djangoApp-list.html'
  model = DjangoApp
  # context_object_name = 'ToDo_list'
  
class AppDetailView(DetailView):
  template_name = 'djangoApp-detail.html'
  model = DjangoApp
  
class AppCreateView(CreateView):
  template_name = 'djangoApp-create.html'
  model = DjangoApp
  fields = ['title', 'body', 'author']
  
class AppUpdateView(UpdateView):
  template_name = 'djangoApp-update.html'
  model = DjangoApp
  fields = ['id', 'title', 'body', 'author']
  
class AppDeleteView(DeleteView):
  template_name = 'djangoApp-delete.html'
  model = DjangoApp
  success_url = reverse_lazy('djangoApp_list')

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "pages/home.html"


class AboutPageView(TemplateView):
    template_name = "pages/about.html"

templates/403_csrf.html
{% extends '_base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/_base.html
{% load static %}

<!DOCTYPE html>

<head>
  <title>Tasks ToDo</title>
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
  <header>
    <ul>
      <a href="{% url 'djangoApp_create' %}">Add a Task ToDo</a>
      <a href="{% url 'djangoApp_list' %}">List ToDo's</a>
    </ul>
  </header>
  <main>
    {% block content %}
    <h2>Someone forgot to put content</h2>
    {% endblock content %}
  </main>
  <footer>

  </footer>
</body>

templates/djangoApp-create.html
{% extends '_base.html' %}

{% block content %}
<h1>ToDo App</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="SAVE">
</form>
{% endblock content %}

templates/djangoApp-delete.html
{% extends '_base.html' %}

{% block content %}
<h1>Delete Task</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <p>Do you REALLY want to delete {{ djangoapp.title }}?</p>
  <input type="submit" value="OK">
</form>
{% endblock content %}

templates/djangoApp-detail.html
{% extends '_base.html' %}

{% block content %}
<h1>Title: {{ djangoapp.title }}</h1>
<p>Description: {{ djangoapp.body }}</p>
<p>Author: {{ djangoapp.author }}</p>
<p class="button"><a href="{% url 'djangoApp_update' djangoapp.pk %}">Update Task</a></p>
<p class="button"><a href="{% url 'djangoApp_delete' djangoapp.pk %}">Delete Task</a></p>

{% endblock content %}

templates/djangoApp-list.html
{% extends '_base.html' %}

{% block content %}
<h1>Todo: </h1>
{% for djangoapp in djangoapp_list %}
<p><a href="{% url 'djangoApp_detail' djangoapp.pk %}">{{ djangoapp.title }}</a></p>
{% endfor %}
{% endblock content %}

templates/djangoApp-update.html
{% extends '_base.html' %}

{% block content %}
<h1>Update Task</h1>
<p> {{djangoapp.id}} </p>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="SAVE">
</form>
{% endblock content %}

templates/pages/about.html
{% extends '_base.html' %}

{% block title %}About page{% endblock %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

templates/pages/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home page{% endblock title %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <img src="{% static 'images/logo.png' %}" class="img-fluid" alt="DjangoX logo"/>
  <p class="lead">A Django starter project with batteries.</p>
</div>
{% endblock content %}